import type { Metadata } from "next";
import "./globals.css";
import { Container, Theme } from "@radix-ui/themes";
import NavBar from "./NavBar";
import Footer from "./Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Theme grayColor="gray" radius="none">
          <NavBar />
          <main className='p-4'>
            <Container>
              {children}
            </Container>
          </main>
        </Theme>
        <Footer />
      </body>
    </html>
  )
}